import { afterEach, describe, expect, it, vi } from 'vitest'
import { api } from './api'
afterEach(() => vi.unstubAllGlobals())
describe('current business batch API', () => {
  it('addresses trees, quality, submissions and correction by business batch only', async () => {
    const fetcher = vi.fn(async (_input: RequestInfo | URL, _init?: RequestInit) => new Response(JSON.stringify({ session: {}, group: {} })))
    vi.stubGlobal('fetch', fetcher)
    await api.treeRun('run/a'); expect(fetcher.mock.calls.at(-1)?.[0]).toBe('/api/tree-runs/run%2Fa')
    await api.batchTree('batch/a'); expect(fetcher.mock.calls.at(-1)?.[0]).toBe('/api/data-batches/batch%2Fa/tree')
    await api.tree('batch/a', 'task/b'); expect(fetcher.mock.calls.at(-1)?.[0]).toBe('/api/data-batches/batch%2Fa/tasks/task%2Fb/tree')
    await api.runQuality('batch/a'); expect(fetcher.mock.calls.at(-1)?.[0]).toBe('/api/data-batches/batch%2Fa/quality')
    await api.taskQuality('batch/a', 'task/b'); expect(fetcher.mock.calls.at(-1)?.[0]).toBe('/api/data-batches/batch%2Fa/tasks/task%2Fb/quality')
    await api.createBuild(['A'], { batch_id: 'one', annotation_version: 'internal-token' })
    expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({ batch_id: 'one', task_ids: ['A'] })
    await api.createQuality('one', ['B'])
    expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({ batch_id: 'one', task_ids: ['B'] })
    await api.createCorrectionSession('one')
    expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({ batch_id: 'one' })
    await api.correctionRecommendation('batch/a')
    expect(fetcher.mock.calls.at(-1)?.[0]).toBe('/api/correction/recommendation?batch_id=batch%2Fa')
  })
  it('sends the loaded revision when editing or resolving retained corrections', async () => {
    const fetcher = vi.fn(async (_input: RequestInfo | URL, _init?: RequestInit) => new Response(JSON.stringify({ group: {}, storage_revision: 8 })))
    vi.stubGlobal('fetch', fetcher)
    await api.patchCorrectionRow('sid', 2, { actions: '{}' }, 7)
    expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({ actions: '{}', expected_revision: 7 })
    const group = await api.patchCorrectionExport('sid', 'g', true, 7)
    expect(group.storage_revision).toBe(8)
    await api.reviewCorrectionGroup('sid', 'g', 'adopt', 8)
    expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({ decision: 'adopt', expected_revision: 8 })
    await api.correctionDatasetExport('sid', 8)
    expect(JSON.parse(String(fetcher.mock.calls.at(-1)?.[1]?.body))).toEqual({ expected_revision: 8 })
  })
})
