import { createRouter, createWebHistory } from 'vue-router'
export default createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', redirect: '/home' },
    { path: '/home', component: () => import('@/views/HomeView.vue') },
    { path: '/pipeline', component: () => import('@/views/PipelineView.vue') },
    { path: '/task-generation', redirect: '/task-generation/scenario-tree' },
    { path: '/task-generation/scenario-tree', component: () => import('@/views/TaskGenerationView.vue') },
    { path: '/task-generation/augmentation', component: () => import('@/views/TaskAugmentationView.vue') },
    { path: '/collection', redirect: '/collection/tree-building' },
    { path: '/collection/phone-factory', component: () => import('@/views/PhoneFactoryCollectionView.vue') },
    { path: '/collection/tree-building', component: () => import('@/views/CollectionView.vue') },
    { path: '/phone-factory', component: () => import('@/views/PhoneFactoryView.vue') },
    { path: '/quality', component: () => import('@/views/QualityView.vue') },
    { path: '/correction', redirect: '/correction/expert-action' },
    { path: '/correction/expert-action', component: () => import('@/views/CorrectionView.vue') },
    { path: '/correction/cot-generation', component: () => import('@/views/CotGenerationView.vue') },
    { path: '/data-publishing', redirect: '/data-publishing/archive' },
    { path: '/data-publishing/archive', component: () => import('@/views/DataPublishingView.vue') },
    { path: '/data-publishing/overview', component: () => import('@/views/TrainingDataOverviewView.vue') },
    { path: '/model-training', redirect: '/model-training/launch' },
    { path: '/model-training/data-mixture', component: () => import('@/views/TrainingDataMixtureView.vue') },
    { path: '/model-training/launch', component: () => import('@/views/ModelTrainingView.vue') },
    { path: '/model-training/validation', component: () => import('@/views/TrainingValidationView.vue') },
    { path: '/model-publishing', component: () => import('@/views/ModelPublishingView.vue') },
    { path: '/model-iteration-evaluation', component: () => import('@/views/ModelIterationEvaluationView.vue') },
  ],
})
